import logging
from gpt4all import GPT4All

# Ativar o logging
logging.basicConfig(level=logging.DEBUG)

class AIModel:
    def __init__(self, model_name="Phi-3-mini-4k-instruct.Q4_0.gguf", device='cpu'):
        self.model = GPT4All(model_name=model_name, device=device)
        logging.info(f"Model {model_name} successfully loaded on device {device}.")

    def generate_response(self, prompt):
        try:
            logging.debug(f"Sending prompt to the model: {prompt}")

            # Gerar a resposta com o modelo GPT4All
            with self.model.chat_session():
                response = self.model.generate(prompt, max_tokens=200)

            logging.debug(f"Response generated by the model: {response}")

            # Verifica se a resposta está vazia
            if not response:
                logging.warning("The response generated by the model was empty.")
                return "Sorry, I couldn't generate a response."

            return response

        except Exception as e:
            logging.error(f"Unexpected error while generating response: {str(e)}")
            return f"An unexpected error occurred: {str(e)}"
