DISCORD_KEY = 'YOUR KEY'
REDDIT_CLIENT_ID = 'YOUR CLIENT ID'
REDDIT_CLIENT_SECRET = 'YOUR KEY'
REDDIT_USER_AGENT = 'YOUR USER'
NEWS_API_KEY = 'YOUR KEY'
WEATHER_API_KEY = 'YOUR KEY'
CHANNEL_ID = 'YOUR CHANNEL'
RIOT_API_KEY = 'YOUR KEY'
FFMPEG_PATH = '/usr/bin/ffmpeg'
LOL_TRIVIA_QUESTIONS = {
    'What is Yasuo\'s brother\'s name?': 'Yone',
    'Who is the creator of League of Legends?': 'Marc Merrill',
    'Which champion has an ability called \'Death Lotus\'?': 'Katarina',
    'What is the name of Darius\' brother?': 'Draven',
    'Which champion can place up to three traps on the map?': 'Jhin',
    'Which champion is known as \'The Master of Shadows\'?': 'Zed',
    'What is Thresh\'s title?': 'The Chain Warden',
    'Who is \'The Steel Shadow\' of Noxus?': 'Camille',
    'Which champion has the passive \'Spiked Shell\'?': 'Rammus',
    'Which champion makes a chicken sound when they die?': 'Sion',
    'Which champion is known as \'The Star Forger\'?': 'Aurelion Sol',
    'What is Garen\'s ultimate ability called?': 'Demacian Justice',
    'Who is the leader of the Vastaya in Ionia?': 'Xayah',
    'Which champion has the ultimate ability \'The Purge\'?': 'Urgot',
    'What is Tryndamere\'s passive ability called?': 'Battle Fury',
    'Which champion is a centaur?': 'Hecarim',
    'What role do most champions with the \'smite\' summoner spell play?': 'Junglers',
    'What is the cursed island in League of Legends called?': 'The Shadow Isles',
    'Who is the champion known as \'The Magical Cat\'?': 'Yuumi',
    'Which champion can bind multiple enemies with her ultimate \'Magnet Storm\'?': 'Rell',
    'Which champion is called \'The Heart of the Freljord\'?': 'Braum',
    'What is the name of Lux\'s ultimate ability?': 'Final Spark',
    'Which champion wields the weapon known as \'The Darkin Blade\'?': 'Aatrox',
    'Who is the champion known as \'The Burning Vengeance\'?': 'Brand',
    'Which champion has a passive ability called \'Concussive Blows\'?': 'Braum',
    'Which champion is nicknamed \'The Eternal Hunters\'?': 'Kindred',
    'What is the name of the capital city of Demacia?': 'Demacia City',
    'Which champion has a shield called \'Black Shield\'?': 'Morgana',
    'Which champion is the leader of the Noxian warbands?': 'Swain',
    'Which champion\'s passive is called \'Unseen Predator\'?': 'Rengar',
    'Who is the champion known as \'The Outlaw\'?': 'Graves',
    'Which champion uses a lantern to capture souls?': 'Thresh',
    'What is the name of the demon that possesses Kalista?': 'Nagakabouros',
    'Which champion is known as \'The Void Walker\'?': 'Kassadin',
    'Which champion has the passive \'Monsoon\'?': 'Janna',
    'Who is the champion known as \'The Exile\'?': 'Riven',
    'What is the name of Zed\'s shadow clones ability?': 'Living Shadow',
    'Which champion is known as \'The Mad Chemist\'?': 'Singed',
    'Which champion throws an ax and picks it up for bonus damage?': 'Draven',
    'Which champion\'s ultimate is called \'The Unstoppable Force\'?': 'Malphite',
    'Who is the Ice Witch in League of Legends?': 'Lissandra',
    'Which champion has the ability \'Summon Tibbers\'?': 'Annie',
    'Which champion is called \'The Yeti Rider\'?': 'Nunu',
    'What is the name of Viego\'s passive ability?': 'Sovereign\'s Domination',
    'Which champion can create a gigantic wall with their ultimate?': 'Anivia',
    'Who is the champion known as \'The Eye of the Void\'?': 'Vel\'Koz',
    'Which champion has a floating book and loves adventure?': 'Yuumi',
    'Which champion uses chakrams as their weapon?': 'Aphelios',
    'Which champion can summon a giant storm as an ultimate ability?': 'Janna',
    'What is the name of Shaco\'s passive ability?': 'Backstab',
    'Which champion\'s ultimate is \'Realm Warp\'?': 'Ryze',
    'Who is known as \'The Hexplosives Expert\'?': 'Ziggs',
    'Which champion has the title \'The Green Father\'?': 'Ivern',
    'Which champion is from the Void and is known as \'The Void Burrower\'?': 'Rek\'Sai',
    'What is the title of the champion Kai\'Sa?': 'Daughter of the Void',
    'Which champion is known as \'The River King\'?': 'Tahm Kench',
    'Which champion is a time-traveling Chronomancer?': 'Zilean',
    'What is the name of Ezreal\'s ultimate ability?': 'Trueshot Barrage',
    'Which champion is known as \'The Berserker\'?': 'Olaf',
    'Which champion throws bouncing bombs?': 'Ziggs',
    'What is the name of Lucian\'s wife?': 'Senna',
    'Who is known as \'The Nine-Tailed Fox\'?': 'Ahri',
    'Which champion is known for the quote \'Time to troll!\'?': 'Trundle',
    'Which champion has a passive called \'Crimson Pact\'?': 'Vladimir',
    'Which champion has an ability called \'Moonlight Vigil\'?': 'Aphelios',
    'Which champion has the ultimate ability \'Feast\'?': 'Cho\'Gath',
    'What is the name of Nasus\'s ultimate?': 'Fury of the Sands',
    'Which champion is known as \'The Spear of Vengeance\'?': 'Kalista',
    'What is the name of Fiora\'s passive?': 'Duelist\'s Dance',
    'Which champion can clone themselves with their passive ability?': 'LeBlanc',
    'What is the name of Kayn\'s scythe?': 'Rhaast',
    'Which champion is known as \'The Bloodharbor Ripper\'?': 'Pyke',
    'What is the name of the oceanic region in Runeterra?': 'Bilgewater',
    'Which champion is called \'The Lady of Luminosity\'?': 'Lux',
    'What is the name of Sylas\'s passive ability?': 'Petricite Burst',
    'Which champion has the ability \'Grand Skyfall\'?': 'Pantheon',
    'Which champion is known as \'The Serpent\'s Embrace\'?': 'Cassiopeia',
    'What is the name of the demonic entity that Aatrox serves?': 'The Darkin',
    'Which champion is the pet of Ivern?': 'Daisy',
    'What is the name of Rumble\'s ultimate ability?': 'The Equalizer',
    'Who is known as \'The Kraken Priestess\'?': 'Illaoi',
    'Which champion is a fallen angel?': 'Kayle',
    'What is the name of Zoe\'s ultimate?': 'Portal Jump',
    'Which champion has an ability called \'Blinding Dart\'?': 'Teemo',
    'Who is the leader of the group known as the Kinkou Order?': 'Shen',
    'Which champion\'s ultimate is called \'Unstoppable Onslaught\'?': 'Sion',
    'What is the name of Renekton\'s ultimate ability?': 'Dominus',
    'Which champion\'s passive is called \'Second Skin\'?': 'Kai\'Sa',
    'What is the name of Evelynn\'s ultimate ability?': 'Last Caress',
    'Which champion is known as \'The Thunder\'s Roar\'?': 'Volibear',
    'What is the name of Ornn\'s passive ability?': 'Living Forge',
    'Which champion is the brother of Ornn?': 'Volibear'
}
LOL_TRIVIA_QUESTIONS_HARD = {
    'What was the original name of League of Legends during early development?': 'Onslaught',
    'Which champion was the first to have an ability that could revive an ally?': 'Zilean',
    'What was the first skin ever released in League of Legends?': 'Black Alistar',
    'Which champion has the longest base attack range in the game?': 'Caitlyn',
    'What is the name of the river that divides Summoner\'s Rift?': 'The Serpentine River',
    'Which champion was removed from the game and never re-released?': 'Gavyn',
    'What was the first item to ever be removed from League of Legends?': 'Heart of Gold',
    'Who was the first champion to be officially reworked?': 'Twisted Fate',
    'Which champion\'s ultimate ability can globally revive allies?': 'Zilean (in early versions)',
    'What was the original name of Blitzcrank\'s \'Rocket Grab\' ability?': 'Hookshot',
    'Which champion was the first to have a toggleable ultimate ability?': 'Swain',
    'Which champion was originally designed to have a pet dragon?': 'Ao Shin',
    'What is the maximum number of stacks that Cho\'Gath\'s ultimate can reach with infinite scaling?': '255',
    'Which champion has the fastest basic attack speed at level 1?': 'Sivir',
    'What is the real name of the shopkeeper in Summoner\'s Rift?': 'Alizabal',
    'What was the first champion to receive a full visual and gameplay update?': 'Sivir',
    'Which champion has the lowest base health in the game?': 'Annie',
    'Which champion was designed by former Riot CEO Marc Merrill?': 'Tryndamere',
    'What is the name of the event that led to the Ruined King\'s return?': 'The Sentinels of Light',
    'Which champion\'s passive ability was originally called \'Dread\' before being renamed?': 'Nocturne',
    'Which champion has the longest range ability in the game?': 'Zac (max range Elastic Slingshot)',
    'Which champion was designed to be a counterpart to Katarina?': 'Talon',
    'Who is the oldest known champion in terms of lore?': 'Ornn',
    'What is the name of the organization that Ekko founded?': 'The Firelights',
    'Which champion has the most different forms and abilities in the game?': 'Aphelios',
    'What is the name of Jhin\'s gun?': 'Whisper',
    'Who was the first champion to be designed with a modern passive that interacts with other abilities?': 'Vladimir',
    'Which champion has the most movement speed modifiers in their kit?': 'Hecarim',
    'Which champion was initially inspired by a Chinese legend of a mischievous monkey?': 'Wukong',
    'Which champion has the highest base attack damage at level 1?': 'Urgot',
    'Which champion had their ultimate removed and replaced with a completely new one in 2019?': 'Aatrox',
    'What is the name of the Freljordian relic that Lissandra seeks?': 'The Heart of the Freljord',
    'Who is the leader of the Trifarix in Noxus?': 'Swain',
    'What was the first dragon type introduced after the elemental rework?': 'Elder Dragon',
    'Which champion\'s ultimate ability has the longest cooldown at rank 1?': 'Karthus (Requiem)',
    'Who is the only champion to have a permanent stealth mechanic?': 'Evelynn',
    'Which champion has a dance animation referencing Michael Jackson?': 'Lucian',
    'What is the name of the floating fortress used by Mordekaiser?': 'The Immortal Bastion',
    'Which champion\'s ability names reference the Four Horsemen of the Apocalypse?': 'Yorick',
    'Which champion was designed to be played without using mana, energy, or fury?': 'Garen',
    'Who was the first champion released in 2021?': 'Viego',
    'What is the name of Rell\'s horse before she fuses with it?': 'Brass',
    'What is the official name of Teemo\'s toxic mushroom ability?': 'Noxious Trap',
    'Which champion was the first to receive an \'Ultimate\' skin?': 'Ezreal (Pulsefire Ezreal)',
    'Which champion has the highest base magic resistance?': 'Galio',
    'What is the name of Shen’s ultimate ability?': 'Stand United',
    'Which champion has the most complex weapon switching system in the game?': 'Aphelios',
    'Which champion has the highest number of lore-related voice interactions?': 'Senna',
    'Who is the true ruler of the Void according to lore?': 'Malzahar',
    'Which champion is the only one to have an ability that removes terrain?': 'Ornn',
}
CHAMPION_ID_MAP = {
    266: "Aatrox", 103: "Ahri", 84: "Akali", 166: "Akshan", 12: "Alistar",
    32: "Amumu", 34: "Anivia", 1: "Annie", 523: "Aphelios", 22: "Ashe",
    136: "Aurelion Sol", 799: "Ambessa", 893: "Aurora", 268: "Azir", 432: "Bard", 200: "Bel'Veth", 53: "Blitzcrank",
    63: "Brand", 201: "Braum", 233: "Briar", 51: "Caitlyn", 164: "Camille",
    69: "Cassiopeia", 31: "Cho'Gath", 42: "Corki", 122: "Darius", 131: "Diana",
    119: "Draven", 36: "Dr. Mundo", 245: "Ekko", 60: "Elise", 28: "Evelynn",
    81: "Ezreal", 9: "Fiddlesticks", 114: "Fiora", 105: "Fizz", 3: "Galio",
    41: "Gangplank", 86: "Garen", 150: "Gnar", 79: "Gragas", 104: "Graves",
    887: "Gwen", 120: "Hecarim", 74: "Heimerdinger", 420: "Illaoi", 39: "Irelia",
    427: "Ivern", 40: "Janna", 59: "Jarvan IV", 24: "Jax", 126: "Jayce",
    202: "Jhin", 222: "Jinx", 145: "Kai'Sa", 429: "Kalista", 43: "Karma",
    30: "Karthus", 38: "Kassadin", 55: "Katarina", 10: "Kayle", 141: "Kayn",
    85: "Kennen", 121: "Kha'Zix", 203: "Kindred", 240: "Kled", 96: "Kog'Maw",
    897: "K'Sante", 7: "LeBlanc", 64: "Lee Sin", 89: "Leona", 876: "Lillia",
    127: "Lissandra", 236: "Lucian", 117: "Lulu", 99: "Lux", 54: "Malphite",
    90: "Malzahar", 57: "Maokai", 11: "Master Yi", 902: "Milio", 21: "Miss Fortune",
    62: "Wukong", 82: "Mordekaiser", 25: "Morgana", 267: "Nami", 75: "Nasus",
    111: "Nautilus", 518: "Neeko", 76: "Nidalee", 895: "Nilah", 56: "Nocturne",
    20: "Nunu & Willump", 2: "Olaf", 61: "Orianna", 516: "Ornn", 80: "Pantheon",
    78: "Poppy", 555: "Pyke", 246: "Qiyana", 133: "Quinn", 497: "Rakan",
    33: "Rammus", 421: "Rek'Sai", 526: "Rell", 888: "Renata Glasc", 58: "Renekton",
    107: "Rengar", 92: "Riven", 68: "Rumble", 13: "Ryze", 360: "Samira",
    113: "Sejuani", 235: "Senna", 147: "Seraphine", 875: "Sett", 35: "Shaco",
    98: "Shen", 102: "Shyvana", 27: "Singed", 14: "Sion", 15: "Sivir",
    72: "Skarner", 37: "Sona", 16: "Soraka", 50: "Swain", 517: "Sylas",
    134: "Syndra", 223: "Tahm Kench", 163: "Taliyah", 91: "Talon", 44: "Taric",
    17: "Teemo", 412: "Thresh", 18: "Tristana", 48: "Trundle", 23: "Tryndamere",
    4: "Twisted Fate", 29: "Twitch", 77: "Udyr", 6: "Urgot", 110: "Varus",
    67: "Vayne", 45: "Veigar", 161: "Vel'Koz", 711: "Vex", 254: "Vi",
    234: "Viego", 112: "Viktor", 8: "Vladimir", 106: "Volibear", 19: "Warwick",
    498: "Xayah", 101: "Xerath", 5: "Xin Zhao", 157: "Yasuo", 777: "Yone",
    83: "Yorick", 350: "Yuumi", 154: "Zac", 238: "Zed", 221: "Zeri",
    115: "Ziggs", 26: "Zilean", 142: "Zoe", 143: "Zyra"
}