DISCORD_KEY = 'YOUR KEY'
REDDIT_CLIENT_ID = 'YOUR CLIENT ID'
REDDIT_CLIENT_SECRET = 'YOUR KEY'
REDDIT_USER_AGENT = 'YOUR USER'
FFMPEG_PATH = '/usr/bin/ffmpeg'
LOL_TRIVIA_QUESTIONS = {
    'What is Yasuo\'s brother\'s name?': 'Yone',
    'Who is the creator of League of Legends?': 'Marc Merrill',
    'Which champion has an ability called \'Death Lotus\'?': 'Katarina',
    'What is the name of Darius\' brother?': 'Draven',
    'Which champion can place up to three traps on the map?': 'Jhin',
    'Which champion is known as \'The Master of Shadows\'?': 'Zed',
    'What is Thresh\'s title?': 'The Chain Warden',
    'Who is \'The Steel Shadow\' of Noxus?': 'Camille',
    'Which champion has the passive \'Spiked Shell\'?': 'Rammus',
    'Which champion makes a chicken sound when they die?': 'Sion',
    'Which champion is known as \'The Star Forger\'?': 'Aurelion Sol',
    'What is Garen\'s ultimate ability called?': 'Demacian Justice',
    'Who is the leader of the Vastaya in Ionia?': 'Xayah',
    'Which champion has the ultimate ability \'The Purge\'?': 'Urgot',
    'What is Tryndamere\'s passive ability called?': 'Battle Fury',
    'Which champion is a centaur?': 'Hecarim',
    'What role do most champions with the \'smite\' summoner spell play?': 'Junglers',
    'What is the cursed island in League of Legends called?': 'The Shadow Isles',
    'Who is the champion known as \'The Magical Cat\'?': 'Yuumi',
    'Which champion can bind multiple enemies with her ultimate \'Magnet Storm\'?': 'Rell',
    'Which champion is called \'The Heart of the Freljord\'?': 'Braum',
    'What is the name of Lux\'s ultimate ability?': 'Final Spark',
    'Which champion wields the weapon known as \'The Darkin Blade\'?': 'Aatrox',
    'Who is the champion known as \'The Burning Vengeance\'?': 'Brand',
    'Which champion has a passive ability called \'Concussive Blows\'?': 'Braum',
    'Which champion is nicknamed \'The Eternal Hunters\'?': 'Kindred',
    'What is the name of the capital city of Demacia?': 'Demacia City',
    'Which champion has a shield called \'Black Shield\'?': 'Morgana',
    'Which champion is the leader of the Noxian warbands?': 'Swain',
    'Which champion\'s passive is called \'Unseen Predator\'?': 'Rengar',
    'Who is the champion known as \'The Outlaw\'?': 'Graves',
    'Which champion uses a lantern to capture souls?': 'Thresh',
    'What is the name of the demon that possesses Kalista?': 'Nagakabouros',
    'Which champion is known as \'The Void Walker\'?': 'Kassadin',
    'Which champion has the passive \'Monsoon\'?': 'Janna',
    'Who is the champion known as \'The Exile\'?': 'Riven',
    'What is the name of Zed\'s shadow clones ability?': 'Living Shadow',
    'Which champion is known as \'The Mad Chemist\'?': 'Singed',
    'Which champion throws an ax and picks it up for bonus damage?': 'Draven',
    'Which champion\'s ultimate is called \'The Unstoppable Force\'?': 'Malphite',
    'Who is the Ice Witch in League of Legends?': 'Lissandra',
    'Which champion has the ability \'Summon Tibbers\'?': 'Annie',
    'Which champion is called \'The Yeti Rider\'?': 'Nunu',
    'What is the name of Viego\'s passive ability?': 'Sovereign\'s Domination',
    'Which champion can create a gigantic wall with their ultimate?': 'Anivia',
    'Who is the champion known as \'The Eye of the Void\'?': 'Vel\'Koz',
    'Which champion has a floating book and loves adventure?': 'Yuumi',
    'Which champion uses chakrams as their weapon?': 'Aphelios',
    'Which champion can summon a giant storm as an ultimate ability?': 'Janna',
    'What is the name of Shaco\'s passive ability?': 'Backstab',
    'Which champion\'s ultimate is \'Realm Warp\'?': 'Ryze',
    'Who is known as \'The Hexplosives Expert\'?': 'Ziggs',
    'Which champion has the title \'The Green Father\'?': 'Ivern',
    'Which champion is from the Void and is known as \'The Void Burrower\'?': 'Rek\'Sai',
    'What is the title of the champion Kai\'Sa?': 'Daughter of the Void',
    'Which champion is known as \'The River King\'?': 'Tahm Kench',
    'Which champion is a time-traveling Chronomancer?': 'Zilean',
    'What is the name of Ezreal\'s ultimate ability?': 'Trueshot Barrage',
    'Which champion is known as \'The Berserker\'?': 'Olaf',
    'Which champion throws bouncing bombs?': 'Ziggs',
    'What is the name of Lucian\'s wife?': 'Senna',
    'Who is known as \'The Nine-Tailed Fox\'?': 'Ahri',
    'Which champion is known for the quote \'Time to troll!\'?': 'Trundle',
    'Which champion has a passive called \'Crimson Pact\'?': 'Vladimir',
    'Which champion has an ability called \'Moonlight Vigil\'?': 'Aphelios',
    'Which champion has the ultimate ability \'Feast\'?': 'Cho\'Gath',
    'What is the name of Nasus\'s ultimate?': 'Fury of the Sands',
    'Which champion is known as \'The Spear of Vengeance\'?': 'Kalista',
    'What is the name of Fiora\'s passive?': 'Duelist\'s Dance',
    'Which champion can clone themselves with their passive ability?': 'LeBlanc',
    'What is the name of Kayn\'s scythe?': 'Rhaast',
    'Which champion is known as \'The Bloodharbor Ripper\'?': 'Pyke',
    'What is the name of the oceanic region in Runeterra?': 'Bilgewater',
    'Which champion is called \'The Lady of Luminosity\'?': 'Lux',
    'What is the name of Sylas\'s passive ability?': 'Petricite Burst',
    'Which champion has the ability \'Grand Skyfall\'?': 'Pantheon',
    'Which champion is known as \'The Serpent\'s Embrace\'?': 'Cassiopeia',
    'What is the name of the demonic entity that Aatrox serves?': 'The Darkin',
    'Which champion is the pet of Ivern?': 'Daisy',
    'What is the name of Rumble\'s ultimate ability?': 'The Equalizer',
    'Who is known as \'The Kraken Priestess\'?': 'Illaoi',
    'Which champion is a fallen angel?': 'Kayle',
    'What is the name of Zoe\'s ultimate?': 'Portal Jump',
    'Which champion has an ability called \'Blinding Dart\'?': 'Teemo',
    'Who is the leader of the group known as the Kinkou Order?': 'Shen',
    'Which champion\'s ultimate is called \'Unstoppable Onslaught\'?': 'Sion',
    'What is the name of Renekton\'s ultimate ability?': 'Dominus',
    'Which champion\'s passive is called \'Second Skin\'?': 'Kai\'Sa',
    'What is the name of Evelynn\'s ultimate ability?': 'Last Caress',
    'Which champion is known as \'The Thunder\'s Roar\'?': 'Volibear',
    'What is the name of Ornn\'s passive ability?': 'Living Forge',
    'Which champion is the brother of Ornn?': 'Volibear'
}