version: '3.8'

services:
  pato-bot:
    container_name: pato-bot
    build: .
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
    volumes:
      - ./data:/app/data
    depends_on:
      - ffmpeg
    command: ["python", "main.py"]

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg
    restart: always