from setuptools import setup, find_packages

setup(
    name='project_pato',
    version='1.0',
    packages=find_packages(),
    install_requires=[
        'aiofiles==24.1.0',
        'aiohappyeyeballs==2.4.6',
        'aiohttp==3.11.13',
        'aiosignal==1.3.2',
        'aiosqlite==0.17.0',
        'annotated-types==0.7.0',
        'anyio==4.8.0',
        'asyncpraw==7.8.1',
        'asyncprawcore==2.4.0',
        'attrs==25.1.0',
        'certifi==2025.1.31',
        'cffi==1.17.1',
        'charset-normalizer==3.4.1',
        'click==8.1.8',
        'colorama==0.4.6',
        'discord==2.3.2',
        'discord.py==2.5.0',
        'distro==1.9.0',
        'frozenlist==1.5.0',
        'gpt4all==2.8.2',
        'gTTS==2.5.4',
        'h11==0.14.0',
        'httpcore==1.0.7',
        'httpx==0.28.1',
        'idna==3.10',
        'jiter==0.8.2',
        'multidict==6.1.0',
        'praw==7.8.1',
        'prawcore==2.4.0',
        'propcache==0.3.0',
        'pycparser==2.22',
        'pydantic==2.10.6',
        'pydantic_core==2.27.2',
        'PyNaCl==1.5.0',
        'requests==2.32.3',
        'setuptools==75.8.0',
        'sniffio==1.3.1',
        'tqdm==4.67.1',
        'typing_extensions==4.12.2',
        'update-checker==0.18.0',
        'urllib3==2.3.0',
        'websocket-client==1.8.0',
        'yarl==1.18.3',
        'youtube-dl==2021.12.17',
        'yt-dlp==2025.2.19',
        'ollama==0.4.7'
    ],
    author='Diogo Correia',
    author_email='diogo.f.correia@protonmail.com',
    description='Discord BOT',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/diogocorreia01/discord_bot_project',
    classifiers=[
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.12',
)
